# Generated by Django 4.2.29 on 2026-03-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afctrack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FittingsDoctrine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'fittings_doctrine',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'can create an MOTD'),)},
        ),
    ]
